### PR TITLE
Clippy fix issues

### LINKED ISSUE #6: Fix issues from Clippy
Fix issues from [Clippy](https://github.com/rust-lang/rust-clippy)
Add instruction for running Clippy at readme

### PR DESCRIPTION
**Pull request by alex-semenyuk**
Close #6

### CODE REVIEW

**Comment by alex-semenyuk** [comment]
@yegor256 could you please take a look

**Comment by yegor256** [comment]
@alex-semenyuk can you add it to GitHub Action `cargo.yml` and `rultor.yml`?

**Comment by alex-semenyuk** [comment]
@yegor256 sure, done

**Comment by yegor256** [comment]
@rultor merge

**Comment by alex-semenyuk** [comment]
@yegor256 could you please retry, should be ok with fmt now.
Btw, should we better configure that every commit triggers pipelines

**Comment by alex-semenyuk** [comment]
@rultor merge

**Comment by alex-semenyuk** [comment]
@rultor merge

**Comment by alex-semenyuk** [comment]
@yegor256 lets try to merge if you are not against

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@alex-semenyuk there was a bug in `.rultor.yml`, I fixed it in a1610f7, but now there conflicts with your branch. please fix them and I'll try to merge again

**Comment by alex-semenyuk** [comment]
@yegor256 done

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@alex-semenyuk one more time, please :(

**Comment by alex-semenyuk** [comment]
@yegor256 done

**Comment by alex-semenyuk** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@alex-semenyuk thanks!

**Pull request merged**
