### PR TITLE
Bugs fixed

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: #49

---

## PR-Codex overview
This PR updates the output message in `fibonacci.rs` and initializes `emu` as mutable in `README.md`. 

### Detailed summary
- Changes the output message in `fibonacci.rs` from "Total is" to "Sum of results is"
- Initializes `emu` as mutable in `README.md`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by EugeneDar** [comment]
I believe that displaying the sum of all results in `fibonacci.rs` is not necessary as it does not provide any useful information and may confuse someone who is new to this repository. In this case, the only association I had was that the program will output the total number of operations. Therefore, it would be better to remove this output or provide a clear explanation of its purpose.

**Comment by EugeneDar** [comment]
In summary, I made the following changes:

1. Added support for mutability to the emu object in the example, as it will be modified.
2. Explicitly included a locator in the Fibonacci example to improve clarity.
3. Adjusted misleading output to provide more accurate information.

@yegor256 please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by EugeneDar** [comment]
@yegor256 please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by EugeneDar** [comment]
@rultor hello

**Pull request merged**
